runtime: nodejs
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1.50
  disk_size_gb: 10

env_variables:
  SQL_USER: admin
  SQL_PASSWORD: tgyhUJ22
  SQL_DATABASE: lp_database
  INSTANCE_CONNECTION_NAME: lp-tool:us-east1:lp-admin-database
beta_settings:
  cloud_sql_instances: lp-tool:us-east1:lp-admin-database